### ISSUE TITLE
Washita test case is causing segmentation fault in clustering

### ISSUE THREAD

**Issue by smithsg84** [parflow/parflow#155]
The Little Washita tests case is causing a segmentation fault in the clustering algorithm on MacOS.

Reported by Laura Condon

![image](https://user-images.githubusercontent.com/19476493/61494641-8e916980-a96b-11e9-9ff6-1df260df6cb5.png)

**Comment by nbengdahl** [comment]
This seems to be caused by the new -nz flag I tried to add. This issue didn't happen during testing but I can reproduce it now. The temporary fix is to use the old pfdist syntax but I'll try to dig into it since apparently I created this problem

**Comment by smithsg84** [comment]
@nbengdahl I don't believe this is related to nz flag change....I have a possible fix for what I think is wrong.  It is in the new clustering algorithm.

**Comment by reedmaxwell** [comment]
So the new fix isn’t backward compatible?

Please excuse the brevity of this message it was sent from my iPhone

On Jul 18, 2019, at 16:25, Nick Engdahl <notifications@github.com<mailto:notifications@github.com>> wrote:


This seems to be caused by the new -nz flag I tried to add. This issue didn't happen during testing but I can reproduce it now. The temporary fix is to use the old pfdist syntax but I'll try to dig into it since apparently I created this problem

**Comment by nbengdahl** [comment]
Steve's fix seems to have done the trick, at least on my Mac. When I tested it a little earlier -nz caused the seg fault but now both ways work (-nz 1 or change computational grid)
