### ISSUE TITLE
ParFlow and CLM output frequency

### ISSUE THREAD

**Issue by kulkarni1** [parflow/parflow#33]
Hello All,
ParFlow's output frequency is controlled by DumpInterval while CLM produces output at every time step. With current NetCDF4 interface, it would be easy if both are written at same output interval and user would have all the ParFlow and CLM variables in single "nc" file. If the CLM output is required more frequently, another interface would be required to be implemented. 
With current interface, I  just need to register the variables and call them in solver_richards.c and user would have CLM and ParFlow output  at ParFlow's output frequency.

**Comment by kulkarni1** [comment]
I have decided to create a separate interface to write CLM output in a separate netCDF file.

**Comment by basileh** [comment]
Hello,
I am Basile HECTOR, I use ParFlow-CLM quite a lot over African catchment. It is often a good pick to chose different output intervals (and therefore output files) for CLM and ParFlow. This is possible using the CLM dump interval key in the tcl. For instance, for long runs over significant domains, I often output PF variables (e.g. pressure & saturation) at a daily time step, while I need CLM fluxes a hourly time step to be able to reconstruct diurnal behavior. 
Doing this, I also think that another different sampling interval could be affected to surface pressure to allow for higher rate overland flow sampling. In the example above, I modified solver_richards.c in my PF version to include the first layer of the pressure field (from which I recalculate overland flow in a post proc step) in large CLM 'C' file output. 
With best,
and thanks for the work!
Basile

**Comment by kulkarni1** [comment]
Hi Basil,
Thank you for your feedback. For the time being I have implemented separate nc interface for clm. With this I tested with CLM dump interval key and I can produce the output at set frequency. 
Regards,
Ketan

**Comment by basileh** [comment]
Thanks Ketan!
Also, are you planning to add some NC to PFB conversion tools as, say, a pftool? Because we have written c code here in Grenoble (IGE), and the computer engineer who's been doing that is willing to implement it into a pftools. Probably starting next week. Unless you've already done it!
Regards,

**Comment by kulkarni1** [comment]
Hi Basile,
I already have one written in python. It can be found in master branch under here
pftools/prepostproc/pfb2nc.py
There is a header in the file for usage instructions. It needs netcdf python bindings. It would be super is is somehow integrated in pftools.
Regards,
Ketan

**Comment by kulkarni1** [comment]
Hi Basile,
I recently uploaded a branch on parflow github called ncCLMoutput. If you are interested, please checkout and give me your feedback. You can refer to Little Washit netcdf test case for NetCDF tcl flags.
Regards,
Ketan

**Comment by basileh** [comment]
Hi Ketan,
Sure, I'll try this asap. let me just a few days, because I'm just starting my position here at IGE.
Thanks for your work!

**Comment by basileh** [comment]
Hi Ketan,
I'm finally trying the washita case in your branch but can't have it to run, while an older test script (water_balance_x.tcl) went through.
I compiled using make:
./configure --prefix=$PARFLOW_DIR --enable-timing --with-clm --with-silo=$SILO_DIR --with-hypre=$HYPRE2_DIR --with-amps=mpi1 --with-netcdf4=/homelocal/quatela/netcdf-c-4.4.1.1/include/netcdf_par.h

And the error when running the tcl script is:
--------------------------------------------------------------------------
mpiexec has exited due to process rank 0 with PID 5787 on
node smos exiting improperly. There are two reasons this could occur:

1. this process did not call "init" before exiting, but others in
the job did. This can cause a job to hang indefinitely while it waits
for all processes to call "init". By rule, if one process calls "init",
then ALL processes must call "init" prior to termination.

2. this process called "init", but exited without calling "finalize".
By rule, all processes that call "init" MUST call "finalize" prior to
exiting or it will be considered an "abnormal termination"

This may have caused other processes in the application to be
terminated by signals sent by mpiexec (as reported here).
--------------------------------------------------------------------------
child process exited abnormally
    while executing
"exec sh /homelocal5/phyrev/_PARFLOW/parflow/parflow_git/parflow/bin/run LW 1 1"
    ("eval" body line 1)
    invoked from within
"eval exec sh $Parflow::PARFLOW_DIR/bin/run  $runname $NumProcs $NumNodes"
    (procedure "pfrun" line 77)
    invoked from within



... Any idea? Did I miss something in the compilation?
Thanks, Basile

**Comment by kulkarni1** [comment]
For configure option --with-netcdf4 you need to give path of installation where library, bin and include folders are and not the header file. So in your case try --with-netcdf4=/homelocal/quatela/netcdf-c-4.4.1.1 
and reconfigure and recompile. That should work.Check under the mentioned path if you have lib, include and bin folders.
Regards,
Ketan

**Comment by kulkarni1** [comment]
By the way which version of HDF5 are you using/ With above error, do you get any netcdf files at all in your output directory or it fails at the start?

**Comment by basileh** [comment]
Yes I was investigating this... I think it's a too old one. Also I don't find the bin files in netcdf...

**Comment by basileh** [comment]
But yeah I do get a netcdf : slope, press_init but can't open it with visit.
the local server we have here is a bit messy with the nc libs . I'll check that and come back to you asap. At least I see where the issue is. 
h5cc -showconfig tells me 1.8.13... too old, right?

**Comment by kulkarni1** [comment]
Hello Basile,
Here are the instructions to install HDF5 parallel version and NetCDF5 parallel version
http://www.unidata.ucar.edu/software/netcdf/docs/getting_and_building_netcdf.html#build_parallel
HDF5 .8.16 or higher should be used.

**Comment by kulkarni1** [comment]
1.8.16

**Comment by kulkarni1** [comment]
The slopes and press init netcdf files are copied as input for this case from top level directories. Model output should look like LW.out.00000.nc and so on.

**Comment by kulkarni1** [comment]
Hi Basile,
I just compiled everything from scratch on my ubuntu laptop(HDF5  1.8.19, netcdf-c-4.5.0 release candidate, hypre and tcl and finally ParFLow) and ran Washita netcdf case. It runs successfully and writes the correct output. If you follow the above mentioned procedure for netcdf4 and HDF5, you should be easily install the libraries yourself .

**Comment by basileh** [comment]
Perfect, thanks, I'm working on it

**Comment by reedmaxwell** [comment]
Thanks for working this issue guy!  One huge priority is to map out mac OS X compilation too.

Reed

Reed M. Maxwell, Ph.D.
Rowlinson Professor of Hydrology
Department of Geology and Geological Engineering
Director, Integrated GroundWater Modeling Center
Colorado School of Mines
http://inside.mines.edu/~rmaxwell/

On Oct 12, 2017, at 8:00 AM, Ketan Kulkarni <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi Basile,
I just compiled everything from scratch on my ubuntu laptop(HDF5 1.8.19, netcdf-c-4.5.0 release candidate, hypre and tcl and finally ParFLow) and ran Washita netcdf case. It runs successfully and writes the correct output. If you follow the above mentioned procedure for netcdf4 and HDF5, you should be easily install the libraries yourself .

**Comment by cswoodward** [comment]
Hi All,

We should make sure to get this info in the user guide.

—Carol

Sent from my iPhone

On Oct 12, 2017, at 2:23 PM, reedmaxwell <notifications@github.com<mailto:notifications@github.com>> wrote:

Thanks for working this issue guy! One huge priority is to map out mac OS X compilation too.

Reed

Reed M. Maxwell, Ph.D.
Rowlinson Professor of Hydrology
Department of Geology and Geological Engineering
Director, Integrated GroundWater Modeling Center
Colorado School of Mines
http://inside.mines.edu/~rmaxwell/

On Oct 12, 2017, at 8:00 AM, Ketan Kulkarni <notifications@github.com<mailto:notifications@github.com><mailto:notifications@github.com>> wrote:


Hi Basile,
I just compiled everything from scratch on my ubuntu laptop(HDF5 1.8.19, netcdf-c-4.5.0 release candidate, hypre and tcl and finally ParFLow) and ran Washita netcdf case. It runs successfully and writes the correct output. If you follow the above mentioned procedure for netcdf4 and HDF5, you should be easily install the libraries yourself .
