### ISSUE TITLE
Change in how Dirichlet bottom boundary conditions work (commit 1a066747)

### ISSUE THREAD

**Issue by cvoter** [parflow/parflow#81]
I’ve been working with a version of parflow from around October 2016 (I don’t have good notes on the exact version) but recently updated to the current version on github. After doing so, I noticed a puzzling change in how my bottom boundary condition works that I’ve traced back to commit 1a066747 from May 1, 2017.

In the model where I observed a change, the domain has a constant DZ (0.1m) with ComputationalGrid.Lower.Z set to 0m. The bottom boundary conditions are set up as follows:

    pfset Patch.bottom.BCPressure.Type  DirEquilRefPatch
    pfset Patch.bottom.BCPressure.Cycle  constant
    pfset Patch.bottom.BCPressure.RefGeom  domain
    pfset Patch.bottom.BCPressure.RefPatch  bottom
    pfset Patch.bottom.BCPressure.alltime.Value  0.0

In versions of parflow before commit 1a066747, this results in a pressure head in the bottom layer that hovers around -0.05m, as I expect. In versions of parflow after commit 1a066747, the pressure head in the bottom layer is suddenly higher, closer to -0.025m. I *think* this is a bug in the newer versions, but I haven’t spent enough time studying the changed file (pfsimulator/parflow_lib/nl_function_eval.c) to spot exactly what the issue is. If it’s not a bug, then I’d appreciate help understanding the change that was made. Thanks in advance!

**Comment by reedmaxwell** [comment]
Hi Carolyn-

Thanks for opening a tag, I also found this bug about a year ago and put in a request as well, though I don’t see it in the system.  If you swap your patch to the top, it will work, but of course this is just a workaround not a fix.

Reed

Reed M. Maxwell, Ph.D.
Rowlinson Professor of Hydrology
Department of Geology and Geological Engineering
Director, Integrated GroundWater Modeling Center
Colorado School of Mines
http://inside.mines.edu/~rmaxwell/

On Jun 7, 2018, at 2:35 PM, Carolyn Voter <notifications@github.com<mailto:notifications@github.com>> wrote:


I’ve been working with a version of parflow from around October 2016 (I don’t have good notes on the exact version) but recently updated to the current version on github. After doing so, I noticed a puzzling change in how my bottom boundary condition works that I’ve traced back to commit 1a06674<https://github.com/parflow/parflow/commit/1a066747d099984f2a0f7f1516f4908de8daad91> from May 1, 2017.

In the model where I observed a change, the domain has a constant DZ (0.1m) with ComputationalGrid.Lower.Z set to 0m. The bottom boundary conditions are set up as follows:

pfset Patch.bottom.BCPressure.Type  DirEquilRefPatch
pfset Patch.bottom.BCPressure.Cycle  constant
pfset Patch.bottom.BCPressure.RefGeom  domain
pfset Patch.bottom.BCPressure.RefPatch  bottom
pfset Patch.bottom.BCPressure.alltime.Value  0.0


In versions of parflow before commit 1a06674<https://github.com/parflow/parflow/commit/1a066747d099984f2a0f7f1516f4908de8daad91>, this results in a pressure head in the bottom layer that hovers around -0.05m, as I expect. In versions of parflow after commit 1a06674<https://github.com/parflow/parflow/commit/1a066747d099984f2a0f7f1516f4908de8daad91>, the pressure head in the bottom layer is suddenly higher, closer to -0.025m. I think this is a bug in the newer versions, but I haven’t spent enough time studying the changed file (pfsimulator/parflow_lib/nl_function_eval.c) to spot exactly what the issue is. If it’s not a bug, then I’d appreciate help understanding the change that was made. Thanks in advance!

**Comment by cvoter** [comment]
Thanks - good to know there's a workaround! Can you clarify what you mean by "swap to the top"? Do you mean when I'm setting all of my BCPressure patches, this one should be specified first? Or I need to define a geometry such that Patch.bottom.BCPressure.RefPatch is the top of that geometry, rather than the bottom?

**Comment by reedmaxwell** [comment]
Hi Carolyn-

I mean use the top boundary instead of the bottom one to specify initial pressure.  For example, say your domain is 10m thick and you have a bottom patch Z0 and a top patch Z1. If you currently set pressure head equal to zero using reference patch Z0 you could also set pressure head equal to -10 at reference patch Z1 with the same net result.

Reed

Reed M. Maxwell, Ph.D.
Rowlinson Professor of Hydrology
Department of Geology and Geological Engineering
Director, Integrated GroundWater Modeling Center
Colorado School of Mines
http://inside.mines.edu/~rmaxwell/

On Jun 11, 2018, at 7:09 AM, Carolyn Voter <notifications@github.com<mailto:notifications@github.com>> wrote:


Thanks - good to know there's a workaround! Can you clarify what you mean by "swap to the top"? Do you mean when I'm setting all of my BCPressure patches, this one should be specified first? Or I need to define a geometry such that Patch.bottom.BCPressure.RefPatch is the top of that geometry, rather than the bottom?

**Comment by cvoter** [comment]
I see - yes, that does give me essentially the same result in versions of parflow before commit 1a06674. Unfortunately, it doesn't seem to help my issue with the latest version of parflow. Just to be clear, in testing I switched from this:

    pfset Patch.bottom.BCPressure.Type  DirEquilRefPatch
    pfset Patch.bottom.BCPressure.Cycle  constant
    pfset Patch.bottom.BCPressure.RefGeom  domain
    pfset Patch.bottom.BCPressure.RefPatch  bottom
    pfset Patch.bottom.BCPressure.alltime.Value  0.0

to this:

    pfset Patch.bottom.BCPressure.Type  DirEquilRefPatch
    pfset Patch.bottom.BCPressure.Cycle  constant
    pfset Patch.bottom.BCPressure.RefGeom  domain
    pfset Patch.bottom.BCPressure.RefPatch  top
    pfset Patch.bottom.BCPressure.alltime.Value  -10.0

and see the same (expected) pressure heads in versions of parflow before commit 1a06674, but also the same (unexpected) pressure heads in the current version of parflow. 

So unless I misunderstood the fix, then until I or someone else spots how to fix the bug I'll continue to use the older version of parflow for models where I have a dirichlet boundary condition.

**Comment by smithsg84** [comment]
This was addressed and PR was closed, see https://github.com/parflow/parflow/pull/83
